#!/bin/bash

project=etools
snapshot_dir=../snapshots
flash_dir=/media/CASPER/flash/projects/$project
filename=$project\_src_$(date +%Y%m%d_%H%M%S).tar.bz2

if [ ! -d $snapshot_dir ]
then
	mkdir $snapshot_dir
fi

tar vjcf ../$filename -X snapshot.ignore ../$project
mv ../$filename $snapshot_dir

if [ -d $flash_dir ]
then
	cp $snapshot_dir/$filename $flash_dir
else
	echo "$flash_dir is not found"
fi
